/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'v3n0m' at '12/11/15 12:13 AM' with Gradle 2.9
 *
 * @author v3n0m, @date 12/11/15 12:13 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
