/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'v3n0m' at '12/11/15 12:13 AM' with Gradle 2.9
 *
 * @author v3n0m, @date 12/11/15 12:13 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
